const traducciones = {
  es: {
    inicio: "Inicio",
    productos: "Productos",
    contacto: "Contacto",
    agregar_carrito: "Agregar al carrito",
    eliminar_carrito: "Eliminar",
    carritoCompras: "Carrito de compras",
    vacio: "El carrito está vacío",
    footer1: "© 2024 Csg Tienda. Todos los derechos reservados.",
    espanol: "Español",
    ingles: "Inglés",
    modo_oscuro: "Modo Oscuro",
    modo_claro: "Modo Claro",
    camisetas: {
      1: "Camiseta básica Csg 1",
      2: "Camiseta básica Csg 2",
      3: "Camiseta Viking Csg",
      4: "Camiseta Boxing Club Csg",
      5: "Camiseta Coach Style Csg",
      6: "Camiseta Dbz Csg",
      7: "Camiseta Ya sois Libres Csg",
      8: "Camiseta Cookie Csg",
      9: "Camiseta Cat Csg",
    },
  },
  en: {
    inicio: "Home",
    productos: "Products",
    contacto: "Contact",
    agregar_carrito: "Add to Cart",
    carritoCompras: "Shopping Cart",
    vacio: "Your cart is empty",
    eliminar_carrito: "Delete",
    footer1: "© 2024 Csg Shop. All rights reserved.",
    espanol: "Spanish",
    ingles: "English",
    modo_oscuro: "Dark Mode",
    modo_claro: "Light Mode",
    camisetas: {
      1: "Basic Csg T-shirt 1",
      2: "Basic Csg T-shirt 2",
      3: "Viking Csg T-shirt",
      4: "Boxing Club Csg T-shirt",  
      5: "Coach Style Csg T-shirt",
      6: "Dbz Csg T-shirt",
      7: "You are free Csg T-shirt",
      8: "Cookie Csg T-shirt",
      9: "Cat Csg T-shirt",
    },
  },
};
